#safe:           false
url:            "http://phillipuniverse.com"
server-port:    4000
markdown:       kramdown
kramdown:
  input: GFM
highlighter:       true
paginate:       10
source:         .
gems: [jekyll-paginate]
